apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge-api
  template:
    metadata:
      labels:
        app: tech-challenge-api
    spec:
      containers:
        - name: tech-challenge-api-container
          image: eltonarodrigues/fiap-tech-challenge-soat-grupo-30:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: fiap-tech-secrets
                  key: db_host
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fiap-tech-secrets
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiap-tech-secrets
                  key: db_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: fiap-tech-secrets
                  key: db_name
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fiap-tech-secrets
                  key: jwt_secret
            - name: USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: fiap-tech-secrets
                  key: user_pool_id
            - name: ADMIN_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: fiap-tech-secrets
                  key: admin_pool_id
            - name: POOL_CLIENT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: fiap-tech-secrets
                  key: pool_client_client_id
            - name: POOL_ADMIN_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: fiap-tech-secrets
                  key: pool_admin_client_id