apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-api-svc
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
  selector:
    app: tech-challenge-api

