apiVersion: v1
kind: PersistentVolume
metadata:
  name: tech-challenge-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard 
  hostPath:
    path: /var/lib/mysql
