<<<<<<< HEAD
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
=======
>>>>>>> adf27ff2c8ad196742a99bd5cc1f6859403f0778
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  tech-challenge-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
<<<<<<< HEAD
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi  # 1G para teste
=======
  resources:
    requests:
      storage: 1Gi  # 1G para teste
>>>>>>> adf27ff2c8ad196742a99bd5cc1f6859403f0778
